[theme]
base                     = "light"
primaryColor             = "#4F46E5"
backgroundColor          = "#FFFFFF"
secondaryBackgroundColor = "#FAFAFF"
textColor                = "#1F2937"
font                     = "sans-serif"

[server]
headless = true

[browser]
gatherUsageStats = false
